# Generated by Django 5.1.2 on 2024-11-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_sku_alter_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='invoice_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
