# Generated by Django 5.1.2 on 2024-12-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('core', '0005_remove_cartorder_user_remove_cartorderitems_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='cartorderitems',
            unique_together={('order', 'product')},
        ),
    ]
