# Generated by Django 5.1.2 on 2024-12-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_qty_cartorderitems_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='quantity',
            new_name='qty',
        ),
    ]
